# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-07 21:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='\u5206\u7c7b')),
                ('isDelete', models.BooleanField(default=False)),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5206\u7c7b',
                'verbose_name_plural': '\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='\u5546\u54c1\u540d\u79f0')),
                ('image', models.ImageField(upload_to='goods/%Y/%m', verbose_name='\u5546\u54c1\u56fe\u7247')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='\u4ef7\u683c')),
                ('isDelete', models.BooleanField(default=False)),
                ('unit', models.CharField(default='500g', max_length=20, verbose_name='\u5355\u4f4d')),
                ('click_nums', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6570')),
                ('desc', models.CharField(max_length=300, verbose_name='\u5546\u54c1\u7b80\u4ecb')),
                ('detail', models.TextField(verbose_name='\u5546\u54c1\u8be6\u60c5')),
                ('stock', models.IntegerField(verbose_name='\u5e93\u5b58')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('goods_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Category')),
            ],
            options={
                'verbose_name': '\u5546\u54c1',
                'verbose_name_plural': '\u5546\u54c1',
            },
        ),
    ]
