# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-07 21:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDatail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='\u4ef7\u683c')),
                ('count', models.IntegerField(verbose_name='\u6570\u91cf')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8ba2\u5355\u8be6\u60c5',
                'verbose_name_plural': '\u8ba2\u5355\u8be6\u60c5',
            },
        ),
        migrations.CreateModel(
            name='OrderForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, verbose_name='\u8ba2\u5355\u7f16\u53f7')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='\u8ba2\u5355\u751f\u6210\u65f6\u95f4')),
                ('isPay', models.BooleanField(default=False, verbose_name='\u662f\u5426\u652f\u4ed8')),
                ('total', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='\u603b\u4ef7')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8ba2\u5355\u5217\u8868',
                'verbose_name_plural': '\u8ba2\u5355\u5217\u8868',
            },
        ),
    ]
